Core\AttributeBundle\Entity\StringAttribute:
    type: entity
    fields:
        stringValue:
            column: string_value
            type: string
            length: 2048
            nullable: true
