core_attribute_create:
    path:     /create
    defaults: { _controller: CoreAttributeBundle:Default:edit }

core_attribute_edit:
    path:     /{id}
    defaults: { _controller: CoreAttributeBundle:Default:edit }

core_attribute_list:
    path:     /
    defaults: { _controller: CoreAttributeBundle:Default:list }


