services:
#    core_attribute.example:
#        class: Core\AttributeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    core_attribute.admin.type:
        class: Core\AttributeBundle\Admin\TypeAdmin
        arguments: [~, Core\AttributeBundle\Entity\Type, CoreAttributeBundle:TypeAdmin]
        calls:
            - [addChild, ['@core_attribute.admin.form_submission']]
            - [setFormTheme, [ ['CoreAttributeBundle:TypeAdmin:form_admin_fields.html.twig'] ]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Dynamic Data', label: 'Forms / Structures' }

    core_attribute.admin.form_submission:
        class: Core\AttributeBundle\Admin\FormSubmissionAdmin
        arguments: [~, Core\AttributeBundle\Entity\FormSubmission, CoreAttributeBundle:AttributeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Dynamic Data', label: 'Form Submissions' }

    core_attribute.admin.records:
        class: Core\AttributeBundle\Admin\AttributeAdmin
        arguments: [~, Core\AttributeBundle\Entity\Attribute, CoreAttributeBundle:AttributeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 'Dynamic Data', label: 'Records' }

    core_attribute.block.service.form:
        class: Core\AttributeBundle\Block\Service\FormBlockService
        arguments:
            - 'Form'
            - '@templating'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: sonata.block }

    ### Event Listener ###
    core_attribute.event_listener_dynamic_entity_listener:
        class: Core\AttributeBundle\EventListener\DynamicEntityListener
        arguments:
            - %sonata.media.media.class%
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    core_attribute.event_listener.form_option_resolve_listener:
        class: Core\AttributeBundle\EventListener\FormOptionResolveListener
        tags:
            - { name: kernel.event_listener, event: core_attribute.option_resolve, method: resolve  }
            - { name: kernel.event_listener, event: core_attribute.option_resolve_attr, method: resolveAttr  }

    ### Event Action ###
    core_attribute.event_action.send_dynamic_form_email:
        class: Core\AttributeBundle\EventAction\SendDynamicFormEmailAction
        calls:
            - [ setContainer, ['@service_container'] ]
        tags:
            - { name: dynamic_event.action }

    ### Form type ###
    core_attribute.form.form_options:
        class: Core\AttributeBundle\Form\FormOptionsType
        arguments:
            - '@core_attribute.form_type_options_provider.provider_chain'
            - '@event_dispatcher'
        tags:
            - { name: form.type, alias: form_options }

    ### Factory ###
    core_attribute.factory.type:
        class: Core\AttributeBundle\Factory\TypeFactory
        arguments:
            - '@core_attribute.form_type_options_provider.provider_chain'

    ### Twig Extensions ###
    core_attribute.twig.extension.attribute:
        class: Core\AttributeBundle\Twig\Extension\AttributeExtension
        arguments:
            - @core_attribute.form_type_options_provider.provider_chain
            - @core_attribute.utils.attribute_value_resolver
        tags:
            - { name: twig.extension }

    ### Form type options provider ###
    core_attribute.form_type_options_provider.provider_chain:
        class: Core\AttributeBundle\FormTypeOptionsProvider\ProviderChain

    core_attribute.form_type_options_provider.form:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Form
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: form }

    core_attribute.form_type_options_provider.text:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Text
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: text }

    core_attribute.form_type_options_provider.textarea:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Textarea
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: textarea }

    core_attribute.form_type_options_provider.email:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Email
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: email }

    core_attribute.form_type_options_provider.integer:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Integer
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: integer }

    core_attribute.form_type_options_provider.money:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Money
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: money }

    core_attribute.form_type_options_provider.number:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Number
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: number }

    core_attribute.form_type_options_provider.url:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Url
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: url }

    core_attribute.form_type_options_provider.choice:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Choice
        tags:
            - { name: dynamic_form.options_provider, alias: choice }

    core_attribute.form_type_options_provider.country:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Country
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: country }

    core_attribute.form_type_options_provider.language:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Language
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: language }

    core_attribute.form_type_options_provider.locale:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Locale
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: locale }

    core_attribute.form_type_options_provider.timezone:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Timezone
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: timezone }

    core_attribute.form_type_options_provider.currency:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Currency
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: currency }

    core_attribute.form_type_options_provider.date:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Date
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: date }

    core_attribute.form_type_options_provider.time:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Time
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: time }

    core_attribute.form_type_options_provider.datetime:
        class: Core\AttributeBundle\FormTypeOptionsProvider\DateTime
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: datetime }

    core_attribute.form_type_options_provider.checkbox:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Checkbox
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: checkbox }

    core_attribute.form_type_options_provider.media:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Media
        publc: false
        arguments:
            - %sonata.media.admin.media.entity%
        tags:
            - { name: dynamic_form.options_provider, alias: core_media_file_input }

    core_attribute.form_type_options_provider.media_selector:
        class: Core\AttributeBundle\FormTypeOptionsProvider\MediaSelector
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: core_attribute_media_admin_selector_type }

    core_attribute.form_type_options_provider.category_selector:
        class: Core\AttributeBundle\FormTypeOptionsProvider\CategorySelector
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: core_attribute_category_admin_selector_type }

    core_attribute.form_type_options_provider.gallery_selector:
        class: Core\AttributeBundle\FormTypeOptionsProvider\GallerySelector
        publc: false
        tags:
            - { name: dynamic_form.options_provider, alias: core_attribute_gallery_admin_selector_type }

    core.media.form.type.admin_selector:
        class: Core\AttributeBundle\Form\MediaAdminSelectorType
        arguments:
            - '@sonata.media.admin.media='
            - '@sonata.admin.form.helper'
        tags:
            - { name: form.type, alias: core_attribute_media_admin_selector_type }

    core.category.form.type.admin_selector:
        class: Core\AttributeBundle\Form\CategoryAdminSelectorType
        arguments:
            - '@sonata.classification.admin.category'
            - '@sonata.admin.form.helper'
        tags:
            - { name: form.type, alias: core_attribute_category_admin_selector_type }

    core.media.form.type.gallery_admin_selector:
        class: Core\AttributeBundle\Form\GalleryAdminSelectorType
        arguments:
            - '@sonata.media.admin.gallery='
            - '@sonata.admin.form.helper'
        tags:
            - { name: form.type, alias: core_attribute_gallery_admin_selector_type }

    ### Model Builder ###
    core_attribute.model_builder.form_submission_index:
        class: Core\AttributeBundle\ModelBuilder\FormSubmissionIndexBuilder
        tags:
            - { name: model_builder, class: 'Core\AttributeBundle\Entity\FormSubmission' }

    ### Utils ###
    core_attribute.utils.attribute_value_resolver:
        class: Core\AttributeBundle\Utils\AttributeValueResolver

    ### Validation ###
    core_attribute.validator.constraints.type_class:
        class: Core\AttributeBundle\Validator\Constraints\TypeClassValidator
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: validator.constraint_validator, alias: core_attribute.validator.constraints.type_class }
