services:
#    core_attribute.example:
#        class: Core\AttributeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    core_attribute.admin.type:
        class: Core\AttributeBundle\Admin\TypeAdmin
        arguments: [~, Core\AttributeBundle\Entity\Type, CoreAttributeBundle:TypeAdmin]
        calls:
            - [addChild, [@core_attribute.admin.form_submission]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: Collections}

    core_attribute.admin.form_submission:
        class: Core\AttributeBundle\Admin\FormSubmissionAdmin
        arguments: [~, Core\AttributeBundle\Entity\FormSubmission, CoreAttributeBundle:FormSubmissionAdmin]
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: Results, show_in_dashboard: false}

    core_attribute.block.service.form:
        class: Core\AttributeBundle\Block\Service\FormBlockService
        arguments:
            - 'Form'
            - @templating
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: sonata.block }