services:
#    core_attribute.example:
#        class: Core\AttributeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    core_attribute.admin.type:
        class: Core\AttributeBundle\Admin\TypeAdmin
        arguments: [~, Core\AttributeBundle\Entity\Type, CoreAttributeBundle:TypeAdmin]
        calls:
            - [addChild, [@core_attribute.admin.form_submission]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: Collections}

    core_attribute.admin.form_submission:
        class: Core\AttributeBundle\Admin\FormSubmissionAdmin
        arguments: [~, Core\AttributeBundle\Entity\FormSubmission, CoreAttributeBundle:FormSubmissionAdmin]
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: Results, show_in_dashboard: false}

    core_attribute.block.service.form:
        class: Core\AttributeBundle\Block\Service\FormBlockService
        arguments:
            - 'Form'
            - @templating
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: sonata.block }

    ### Form type ###
    core_attribute.form.form_options:
        class: Core\AttributeBundle\Form\FormOptionsType
        arguments:
            - @core_attribute.form_type_options_provider.provider_chain
        tags:
            - { name: form.type, alias: form_options }

    ### Factory ###
    core_attribute.factory.type:
        class: Core\AttributeBundle\Factory\TypeFactory
        arguments:
            - @core_attribute.form_type_options_provider.provider_chain

    ### Form type options provider ###
    core_attribute.form_type_options_provider.provider_chain:
        class: Core\AttributeBundle\FormTypeOptionsProvider\ProviderChain

    core_attribute.form_type_options_provider.form:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Form
        tags:
            - { name: dynamic_form.options_provider, alias: form }

    core_attribute.form_type_options_provider.text:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Text
        tags:
            - { name: dynamic_form.options_provider, alias: text }

    core_attribute.form_type_options_provider.textarea:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Textarea
        tags:
            - { name: dynamic_form.options_provider, alias: textarea }

    core_attribute.form_type_options_provider.email:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Email
        tags:
            - { name: dynamic_form.options_provider, alias: email }

    core_attribute.form_type_options_provider.integer:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Integer
        tags:
            - { name: dynamic_form.options_provider, alias: integer }

    core_attribute.form_type_options_provider.money:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Money
        tags:
            - { name: dynamic_form.options_provider, alias: money }

    core_attribute.form_type_options_provider.number:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Number
        tags:
            - { name: dynamic_form.options_provider, alias: number }

    core_attribute.form_type_options_provider.url:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Url
        tags:
            - { name: dynamic_form.options_provider, alias: url }