services:
#    core_attribute.example:
#        class: Core\AttributeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    core_attribute.admin.type:
        class: Core\AttributeBundle\Admin\TypeAdmin
        arguments: [~, Core\AttributeBundle\Entity\Type, CoreAttributeBundle:TypeAdmin]
        calls:
            - [addChild, [@core_attribute.admin.form_submission]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: Collections}

    core_attribute.admin.form_submission:
        class: Core\AttributeBundle\Admin\FormSubmissionAdmin
        arguments: [~, Core\AttributeBundle\Entity\FormSubmission, CoreAttributeBundle:FormSubmissionAdmin]
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Form, label: Results, show_in_dashboard: false}

    core_attribute.block.service.form:
        class: Core\AttributeBundle\Block\Service\FormBlockService
        arguments:
            - 'Form'
            - @templating
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: sonata.block }

    ### Event Listener ###
    core_attribute.event_listener_dynamic_entity_listener:
        class: Core\AttributeBundle\EventListener\DynamicEntityListener
        arguments:
            - %sonata.media.media.class%
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    core_attribute.event_listener.form_option_resolve_listener:
        class: Core\AttributeBundle\EventListener\FormOptionResolveListener
        tags:
            - { name: kernel.event_listener, event: core_attribute.option_resolve, method: resolve  }
            - { name: kernel.event_listener, event: core_attribute.option_resolve_attr, method: resolveAttr  }

    ### Form type ###
    core_attribute.form.form_options:
        class: Core\AttributeBundle\Form\FormOptionsType
        arguments:
            - @core_attribute.form_type_options_provider.provider_chain
            - @event_dispatcher
        tags:
            - { name: form.type, alias: form_options }

    ### Factory ###
    core_attribute.factory.type:
        class: Core\AttributeBundle\Factory\TypeFactory
        arguments:
            - @core_attribute.form_type_options_provider.provider_chain

    ### Form type options provider ###
    core_attribute.form_type_options_provider.provider_chain:
        class: Core\AttributeBundle\FormTypeOptionsProvider\ProviderChain

    core_attribute.form_type_options_provider.form:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Form
        tags:
            - { name: dynamic_form.options_provider, alias: form }

    core_attribute.form_type_options_provider.text:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Text
        tags:
            - { name: dynamic_form.options_provider, alias: text }

    core_attribute.form_type_options_provider.textarea:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Textarea
        tags:
            - { name: dynamic_form.options_provider, alias: textarea }

    core_attribute.form_type_options_provider.email:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Email
        tags:
            - { name: dynamic_form.options_provider, alias: email }

    core_attribute.form_type_options_provider.integer:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Integer
        tags:
            - { name: dynamic_form.options_provider, alias: integer }

    core_attribute.form_type_options_provider.money:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Money
        tags:
            - { name: dynamic_form.options_provider, alias: money }

    core_attribute.form_type_options_provider.number:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Number
        tags:
            - { name: dynamic_form.options_provider, alias: number }

    core_attribute.form_type_options_provider.url:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Url
        tags:
            - { name: dynamic_form.options_provider, alias: url }

    core_attribute.form_type_options_provider.choice:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Choice
        tags:
            - { name: dynamic_form.options_provider, alias: choice }

    core_attribute.form_type_options_provider.country:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Country
        tags:
            - { name: dynamic_form.options_provider, alias: country }

    core_attribute.form_type_options_provider.language:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Language
        tags:
            - { name: dynamic_form.options_provider, alias: language }

    core_attribute.form_type_options_provider.locale:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Locale
        tags:
            - { name: dynamic_form.options_provider, alias: locale }

    core_attribute.form_type_options_provider.timezone:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Timezone
        tags:
            - { name: dynamic_form.options_provider, alias: timezone }

    core_attribute.form_type_options_provider.currency:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Currency
        tags:
            - { name: dynamic_form.options_provider, alias: currency }

    core_attribute.form_type_options_provider.date:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Date
        tags:
            - { name: dynamic_form.options_provider, alias: date }

    core_attribute.form_type_options_provider.time:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Time
        tags:
            - { name: dynamic_form.options_provider, alias: time }

    core_attribute.form_type_options_provider.datetime:
        class: Core\AttributeBundle\FormTypeOptionsProvider\DateTime
        tags:
            - { name: dynamic_form.options_provider, alias: datetime }

    core_attribute.form_type_options_provider.checkbox:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Checkbox
        tags:
            - { name: dynamic_form.options_provider, alias: checkbox }

    core_attribute.form_type_options_provider.media:
        class: Core\AttributeBundle\FormTypeOptionsProvider\Media
        arguments:
            - %sonata.media.admin.media.entity%
        tags:
            - { name: dynamic_form.options_provider, alias: core_media_file_input }